POST http://localhost:3001/upload
content-type: application/json
{
    "msg":"你好中国"
}

###
POST http://localhost:3001/api/user
content-type: application/json
{
    "type": 0,
    "name": "Admin",
    "email": "875658697@qq.com",
    "password": "bdc8bd3183a41ddf7c680744b77ecb5f",
    "disability": []
}

###
GET http://localhost:3001/api/user/4

###
POST http://localhost:3001/api/user
content-type: application/json
{
    "type": 1,
    "name": "蒋中文",
    "email": "oiiaioiiiai@nb.com",
    "password": "698d51a19d8a121ce581499d7b701668",
    "disability": []
}

###
GET http://localhost:3001/api/user?mode=find&email=875658697@qq.com

###
GET http://localhost:3001/api/notification/875658697@qq.com

### 
POST http://localhost:3001/api/notification/875658697@qq.com
content-type: application/json

{
    "content": "新消息",
    "from": "server"
}

### 
POST http://localhost:3001/api/notification/875658697@qq.com
content-type: application/json

{
    "content": "新全局消息",
    "from": "test",
    "location": {"latitude": 23.074334, "longitude": 114.415251, "altitude": 20}
}

###
GET http://localhost:3001/api/global/notification/

### 删除所有通知
DELETE http://localhost:3001/api/notification/875658697@qq.com

### 删除通知
DELETE http://localhost:3001/api/notification/875658697@qq.com/1743834867634

### 删除全局通知
DELETE http://localhost:3001/api/global/notification/1743824694429

### 删除所有全局通知
DELETE http://localhost:3001/api/global/notification/

### 获取所有帖子
GET http://localhost:3001/api/post

### 获取特定时间的帖子
GET http://localhost:3001/api/post/1740805721290
Content-Type: application/json

### 添加新帖子
POST http://localhost:3001/api/post
Content-Type: application/json

{
  "location": {"latitude": 23.074334, "longitude": 114.415251, "altitude": 20},
  "title": "Sample Post 3",
  "content": "Sample Post Content",
  "disability": ["vision", "hearing"],
  "author_id": 1,
  "image_count": 1
}

### 删除特定时间的帖子
DELETE http://localhost:3001/api/post/1741437760848
Content-Type: application/json

### 获取特定时间的帖子详情
GET http://localhost:3001/api/post/1740805721290/detail/
Content-Type: application/json

### 获取聊天列表
GET http://localhost:3001/api/chat/list/4
Content-Type: application/json

### 发送消息
POST http://localhost:3001/api/chat/1743836997193
Content-Type: application/json

{
    "id": "0",
    //"name": "Admin",
    "message": "你好"
}

### 获取聊天
GET http://localhost:3001/api/chat/1743836997193
Content-Type: application/json