POST http://localhost:3001/upload
content-type: application/json
{
    "msg":"你好中国"
}

###
POST http://localhost:3001/api/user
content-type: application/json
{
    "type": 0,
    "name": "Admin",
    "email": "875658697@qq.com",
    "password": "bdc8bd3183a41ddf7c680744b77ecb5f",
    "disability": []
}

###
GET http://localhost:3001/api/user/0

###
POST http://localhost:3001/api/user
content-type: application/json
{
    "type": 1,
    "name": "蒋中文",
    "email": "oiiaioiiiai@nb.com",
    "password": "698d51a19d8a121ce581499d7b701668",
    "disability": []
}

###
GET http://localhost:3001/api/user?mode=find&email=875658697@qq.com

###
GET http://localhost:3001/api/notification/875658697@qq.com

### 
POST http://localhost:3001/api/notification/875658697@qq.com
content-type: application/json

{
    "notification": {
        "content": "新消息",
        "from": "server"
    }
}

### 删除所有通知
DELETE http://localhost:3001/api/notification/875658697@qq.com

### 获取所有帖子
GET http://localhost:3001/api/post

### 获取特定时间的帖子
GET http://localhost:3001/api/post/1738563476000
Content-Type: application/json

### 添加新帖子
POST http://localhost:3001/api/post
Content-Type: application/json

{
  "location": {"latitude": 114.420134, "longitude": 23.07175, "altitude": 20},
  "title": "Sample Post2",
  "disability": ["vision", "hearing"],
  "author_id": 1,
  "image_count": 1
}

### 删除特定时间的帖子
DELETE http://localhost:3001/api/post/1738563476000
Content-Type: application/json